name: FAQ chatbot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build: 
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME}}
        password: ${{ secrets.DOCKER_PASSWORD}}

    - name: Docker build
      run: docker build -t ${{ secrets.DOCKER_USERNAME}}/faq-chatbot:latest .

    - name: Docker push
      run: docker push ${{ secrets.DOCKER_USERNAME}}/faq-chatbot:latest 

  
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/

    - name: Set up Kubeconfig
      run: |
        echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > $HOME/.kube/config 
        chmod 600 $HOME/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployment.yml
        kubectl apply -f service.yml

    - name: Verify Deployment
      run: |
        kubectl rollout status deployment/faq-chatbot
        kubectl get services faq-chatbot-service        

    wait a sec, is it run on my local computer ,but i push in github, and 
what is:  # On your local machine where you have kubectl configured:
cat ~/.kube/config | base64
isn't it provide key to local machine not github      